spring:
  profiles:
    active: local

---
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094
    template:
      default-topic: library-events
  config:
    activate:
      on-profile: local

---
spring:
  kafka:
    producer:
      #below is the secured cluster server and it will have client.keystore.jws ,and client.truststore.jws file
      #because this is producer and act as client for brokers which is using ssl with server.keystore.jws& server.truststore.jks files bith should have signned secured file using cert file
      bootstrap-servers: localhost:9095,localhost:9096,localhost:9097
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      ssl:
        trust-store-location: file:/ filepath for client.truststore.jws
        trust-store-password: password
        key-store-location: file:/ filepath for client.keystore.jws
        key-store-password: password
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
        security:
          protocol: SSL
        ssl.endpoint.identification.algorithms:
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094
    template:
      default-topic: library-events
  config:
    activate:
      on-profile: nonprod


